apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "amundsen.fullname" . }}-{{ .Values.preview.serviceName }}
  labels:
    app: {{ template "amundsen.name" . }}
    component: {{ .Values.preview.serviceName }}
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "amundsen.name" . }}
      component: {{ .Values.preview.serviceName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with default .Values.podAnnotations .Values.preview.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "amundsen.name" . }}
        component: {{ .Values.preview.serviceName }}
        release: {{ .Release.Name }}
    spec:
      {{- with default .Values.nodeSelector .Values.preview.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.preview.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.preview.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.frontEnd.oidcEnabled }}
        - name: oidc-config
          secret:
            secretName: oidc-config
      {{- end }}
        - name: preview
          persistentVolumeClaim:
            claimName: preview-pvc
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.preview.serviceName }}
        image: {{ .Values.preview.image }}:{{ .Values.preview.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: PREVIEW_FILE_REPO
          value: {{ if .Values.preview.previewFileDir }}{{ .Values.preview.previewFileDir }}{{ else }}/var/amundsen/preview_data{{ end }}
        {{- if .Values.frontEnd.oidcEnabled }}
        - name: FLASK_OIDC_CLIENT_SECRETS
          value: /etc/client_secrets.json
        - name: FLASK_OIDC_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: oidc-config
              key: OIDC_CLIENT_SECRET
        {{- end }}
        livenessProbe:
          httpGet:
            path: "/healthcheck"
            port: 5002
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        {{- if .Values.frontEnd.oidcEnabled }}
          - name: oidc-config
            mountPath: /etc/client_secrets.json
            subPath: client_secrets.json
        {{- end }}
          - name: preview
            mountPath: {{ if .Values.preview.previewFileDir }}{{ .Values.preview.previewFileDir }}{{ else }}/var/amundsen/preview_data{{ end }}
        {{- with .Values.metadata.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
