apiVersion: v1
kind: Service
metadata:
  name: {{ template "amundsen.fullname" . }}-neo4j-lb
  labels:
    app: {{ template "amundsen.name" . }}
    component: neo4j
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: {{ template "amundsen.name" . }}
    component: neo4j
  ports:
    - port: 7687
      protocol: TCP
      name: bolt-port
      targetPort: 7687
    - port: 7474
      protocol: TCP
      name: neo4j-portal
      targetPort: 7474
  type: LoadBalancer
