apiVersion: v1
description: Amundsen is a metadata driven application for improving the productivity of data analysts, data scientists and engineers when interacting with data.
name: amundsen
version: 2.0.0
icon: https://github.com/kylg/amundsen_azure/blob/master/docs/img/logos/amundsen_logo_on_light.svg
home: https://github.com/kylg/amundsen_azure
maintainers:
  - name: kylg
    email: info@kylg.org
sources:
  - https://github.com/kylg/amundsen_azure
keywords:
  - metadata
  - data